import json
import uuid
import time
import boto3
import os
from chalicelib.ingestion.kag_loader import get_prepared_kag_batch
from chalicelib.models.feedback import FeedbackModel
from boto3.dynamodb.conditions import Attr

import json
        
class FeedbackAnalysisPipeline:
    def __init__(self, ingestor, sanitizer, security, translator, analyzer, persistence, logger, s3_storage, summarizer=None):
        # 1. Dependencies
        self.ingestor = ingestor
        self.sanitizer = sanitizer
        self.security = security
        self.translator = translator
        self.analyzer = analyzer
        self.persistence = persistence  
        self.logger = logger
        self.s3_storage = s3_storage
        self.summarizer = summarizer 
        
        # 2. Cloud Configuration
        # Ensure we use the same naming convention everywhere
        import boto3
        self.bucket = s3_storage.bucket_name
        self.region = "us-east-1" 
        self.dynamodb = boto3.resource('dynamodb', region_name=self.region)
        self.s3_client = boto3.client('s3', region_name=self.region)
        self.lambda_client = boto3.client('lambda', region_name=self.region)
        
        self.logger.log_event("PIPELINE", "INFO", "Pipeline Architecture Initialized")

    def run(self, raw_input: dict):
        # 1. MASTER ID SYNC
        user_id = raw_input.get('user_id', 'admin')
        current_feedback_id = raw_input.get('feedback_id')
        if not current_feedback_id:
            job_id = uuid.uuid4().hex[:8]
            current_feedback_id = f"{user_id}_{job_id}"

        image_data = raw_input.get('image_data')
        ext = "txt"
        if image_data and 'name' in image_data:
            ext = image_data['name'].split('.')[-1]
        
        file_key = f"uploads/{current_feedback_id}.{ext}"
        
        # --- TRACE LOG: ID & PATH ---
        print(f"🚀 [TRACE] Starting Pipeline for ID: {current_feedback_id}")
        print(f"📂 [TRACE] Target S3 Path: {self.bucket}/{file_key}")

        # 2. 🎯 PRE-SEED DYNAMODB RECORD
        table = self.dynamodb.Table("Analysis_Summaries")
        try:
            table.put_item(Item={
                'feedback_id': current_feedback_id,
                'user_id': user_id,
                'status': 'PROCESSING',
                'timestamp': str(time.time()),
                'master': '✅ Orchestrator Initialized' 
            })
            print(f"✅ [TRACE] DynamoDB Seeded successfully.")
        except Exception as e:
            print(f"❌ [TRACE] DynamoDB Seed FAILED: {str(e)}")

        # 3. UPLOAD TO S3 (The Trigger Point)
        try:
            body_content = image_data['bytes'] if image_data else raw_input.get('text', '')
            
            # --- TRACE LOG: Content Check ---
            content_type = "IMAGE" if image_data else "TEXT"
            print(f"📤 [TRACE] Uploading {content_type} to S3. Content length: {len(body_content)}")
            
            self.s3_client.put_object(
                Bucket=self.bucket,
                Key=file_key,
                Body=body_content,
                # CRITICAL: If this metadata is missing, the Master Lambda won't know which DB row to update
                Metadata={"feedback_id": current_feedback_id}
            )
            print(f"📡 [TRACE] S3 PutObject Successful. Metadata sent: {current_feedback_id}")
            
        except Exception as e:
            print(f"❌ [TRACE] S3 UPLOAD CRITICAL ERROR: {str(e)}")
            yield 0.0, f"❌ S3 Error: {str(e)}"
            return

        # 4. POLLING WITH LIVE DATA
        results = {"status": "IN_PROGRESS", "feedback_id": current_feedback_id}
        
        for i in range(60): 
            time.sleep(1.5)
            
            response = table.get_item(Key={'feedback_id': current_feedback_id})
            data = response.get('Item', {})
            
            # --- TERMINAL MONITOR ---
            # If 'Keys Found' stays at 5 keys, the Lambdas are NOT writing back.
            print(f"🔍 [POLL {i}] ID: {current_feedback_id} | Status: {data.get('status')} | Keys: {list(data.keys())}")

            results["summary"] = data
            progress = min((i + 1) / 45, 0.99)
            
            msg = "📡 Master is directing traffic..."
            if data.get('audio_path'):
                msg = "🎙️ Voice synthesis ready. Finishing up..."
            elif data.get('summary'):
                msg = "🤖 Summary generated by Mistral AI."
            elif data.get('sentiment'):
                msg = "🧠 Sentiment analysis complete."
            elif data.get('text'):
                msg = "📸 OCR/Input text extracted."
            elif data.get('master'):
                msg = "🎮 Orchestrator active (Hub-and-Spoke)."

            yield progress, msg
            yield progress, results 
            
            # Check for Final Completion (Normalized for AWS/Local)
            db_status = str(data.get('status', '')).upper()
            if db_status in ['COMPLETED', 'COMPLETE'] or data.get('summary'):
                results["status"] = "COMPLETE"
                yield 1.0, "✅ All Cloud Workers finished!"
                yield 1.0, results
                return

        results["status"] = "TIMEOUT"
        yield 1.0, results

    def trigger_kag_ingestion(self, base_path, folder_name="Email", limit=5):
        """
        KAG Trigger: Initiates the Full Chain (OCR -> Translate -> Sentiment -> Summary -> Speech).
        """
      
        # 1. Prepare Batch from VMware Local Disk
        samples = get_prepared_kag_batch(base_path, folder_name=folder_name, limit=limit)
        
        sample_ids = []
        table = self.dynamodb.Table("Analysis_Summaries")
        lambda_client = boto3.client('lambda', region_name=self.region)

        for sample in samples:
            fid = sample['feedback_id']
            sample_ids.append(fid)
            
            # 2. Upload to S3 (The "Event" Source)
            file_key = f"kaggle_tobacco/{folder_name}/{sample['filename']}"
            self.s3_client.put_object(
                Bucket=self.bucket,
                Key=file_key,
                Body=sample['image_bytes'],
                Metadata={"feedback_id": fid}
            )

            # 3. Initialize DynamoDB with 'PROCESSING' state
            table.put_item(Item={
                'feedback_id': fid,
                'status': 'PROCESSING',
                'dataset_type': f'KAG_{folder_name.upper()}',
                'timestamp': str(time.time()),
                'master': '🚀 Full-Chain Pipeline Started'
            })

            # 4. 🎯 THE BATON PASS: Trigger the KAG Worker (Cloud Side)
            # This worker will then trigger OCR -> Analysis -> Speech
            relay_payload = {
                "feedback_id": fid,
                "bucket": self.bucket,
                "image_url": f"s3://{self.bucket}/{file_key}",
                "folder": folder_name
            }
            
            try:
                lambda_client.invoke(
                    FunctionName='kag_worker', # Matches your cloud worker name
                    InvocationType='Event',    # Asynchronous
                    Payload=json.dumps(relay_payload).encode('utf-8')
                )
                print(f"📡 [KAG] Chain triggered for {fid}")
            except Exception as e:
                print(f"❌ [KAG] Lambda Trigger Failed for {fid}: {e}")

        return {
            "status": "success",
            "sample_ids": sample_ids,
            "message": f"Successfully initiated full-chain processing for {len(sample_ids)} docs."
        }

    def trigger_mnist_ingestion(self, digit="0", limit=3):
        import tensorflow as tf
        import os
        import json
        import time
        import logging

        logger = logging.getLogger("AWS_Pipeline")
        TFRECORD_PATH = "/home/edwin/projects/feedback_analyzer/data/tfrecords/mnist_standard.tfrecord"
        
        print(f"🚀 [DEBUG] Starting MNIST Ingestion for digit: {digit}", flush=True)

        feature_description = {
            'image': tf.io.FixedLenFeature([], tf.string), 
            'label': tf.io.FixedLenFeature([], tf.int64),
            'filename': tf.io.FixedLenFeature([], tf.string),
        }

        try:
            raw_dataset = tf.data.TFRecordDataset(TFRECORD_PATH)
            parsed_dataset = raw_dataset.map(lambda x: tf.io.parse_single_example(x, feature_description))
            
            target_digit = int(digit)
            digit_samples = parsed_dataset.filter(lambda x: x['label'] == target_digit).shuffle(100).take(limit)

            batch_results = []
            for i, record in enumerate(digit_samples):
                fid = f"mnist_{digit}_{int(time.time())}_{i}"
                img_bytes = record['image'].numpy() 
                s3_key = f"datasets/mnist/{digit}/{fid}.png"

                # 1. S3 Upload
                print(f"📤 [DEBUG] Uploading to S3: {s3_key}...", flush=True)
                self.s3_client.put_object(
                    Bucket=self.bucket,
                    Key=s3_key,
                    Body=img_bytes,
                    ContentType='image/png'
                )

                # 2. Lambda Trigger
                relay_payload = {
                    "feedback_id": fid,
                    "label": str(digit),
                    "image_url": f"s3://{self.bucket}/{s3_key}",
                    "bucket": self.bucket
                }

                print(f"📡 [DEBUG] Triggering Lambda for {fid}...", flush=True)
                self.lambda_client.invoke(
                    FunctionName='mnist_ingestor_worker',
                    InvocationType='Event',
                    Payload=json.dumps(relay_payload).encode('utf-8')
                )
                batch_results.append(fid)
                
                # 🎯 NEW: Yield progress so the UI spinner stays active and informed
                yield (i + 1) / limit, f"Uploaded {i+1}/{limit} samples..."

            print(f"✅ [DEBUG] Batch Complete: {batch_results}", flush=True)
            
            # 🎯 CRITICAL CHANGE: Yield the final result dictionary at 1.0 (100%)
            yield 1.0, {"status": "success", "sample_ids": batch_results}

        except Exception as e:
            print(f"❌ [DEBUG] Error: {str(e)}", flush=True)
            yield 0.0, {"status": "error", "message": str(e)}
            
    def get_user_feedback(self, username):
        """Used by HistoryUI to list previous analyses."""
        try:
            table = self.dynamodb.Table('Analysis_Summaries')
            response = table.scan(FilterExpression=Attr('user_id').eq(username))
            items = response.get('Items', [])
            return sorted(items, key=lambda x: x.get('timestamp', ''), reverse=True)
        except Exception as e:
            self.logger.log_event("DATABASE", "ERROR", f"Error: {e}")
            return []

    def _get_table_data(self, table_name, feedback_id):
        """Matches the 'feedback_id' HASH key found in describe-table."""
        try:
            table = self.dynamodb.Table(table_name)
            response = table.get_item(Key={'feedback_id': feedback_id}) # Fixed key name
            return response.get('Item')
        except Exception as e:
            self.logger.log_event("DB_POLLING", "ERROR", f"Error: {e}")
            return None