import json
import uuid
import time
import boto3
import os
from chalicelib.models.feedback import FeedbackModel
from .interfaces.pipeline import IAnalysisPipeline

class FeedbackAnalysisPipeline:
    # Add 'summarizer=None' to the end of the arguments list
    def __init__(self, ingestor, sanitizer, security, translator, analyzer, persistence, logger, s3_storage, summarizer=None):
        # 1. Dependencies
        self.ingestor = ingestor
        self.sanitizer = sanitizer
        self.security = security
        self.translator = translator
        self.analyzer = analyzer
        self.persistence = persistence  
        self.logger = logger
        self.s3_storage = s3_storage
        self.summarizer = summarizer # <--- Store the new summarizer component
        
        # 2. Cloud Configuration
        self.bucket = s3_storage.bucket_name
        self.region = "us-east-1" 
        self.dynamodb = boto3.resource('dynamodb', region_name=self.region)
        self.s3_client = boto3.client('s3')
        
        # Professional initialization log
        self.logger.log_event("PIPELINE", "INFO", "Pipeline Architecture Initialized")

    def run(self, raw_input: dict):
        # 1. MASTER ID SYNC
        user_id = raw_input.get('user_id', 'admin')
        current_feedback_id = raw_input.get('feedback_id')
        if not current_feedback_id:
            job_id = uuid.uuid4().hex[:8]
            current_feedback_id = f"{user_id}_{job_id}"

        image_data = raw_input.get('image_data')
        ext = "txt"
        if image_data and 'name' in image_data:
            ext = image_data['name'].split('.')[-1]
        
        file_key = f"uploads/{current_feedback_id}.{ext}"
        
        # 2. 🎯 PRE-SEED DYNAMODB RECORD (Instant Master Tick)
        # We do this before S3 upload so the UI turns the 🎮 Green immediately.
        table = self.dynamodb.Table("Analysis_Summaries")
        table.put_item(Item={
            'feedback_id': current_feedback_id,
            'user_id': user_id,
            'status': 'PROCESSING',
            'timestamp': str(time.time()),
            'master': '✅ Orchestrator Initialized' 
        })

        # 3. UPLOAD TO S3
        try:
            body_content = image_data['bytes'] if image_data else raw_input.get('text', '')
            self.s3_client.put_object(
                Bucket=self.bucket,
                Key=file_key,
                Body=body_content,
                Metadata={"feedback_id": current_feedback_id}
            )
        except Exception as e:
            yield 0.0, f"❌ S3 Error: {str(e)}"
            return

        # 4. POLLING WITH LIVE DATA & DYNAMIC MESSAGES
        results = {"status": "IN_PROGRESS", "feedback_id": current_feedback_id}
        
        # 60 attempts x 1.5s = 90s total window for "The Baton Show"
        for i in range(60): 
            time.sleep(1.5)
            
            # Fetch latest state from Cloud
            response = table.get_item(Key={'feedback_id': current_feedback_id})
            data = response.get('Item', {})
            
            # Update results with fresh data for the UI Tracker
            results["summary"] = data 
            progress = min((i + 1) / 45, 0.99) # Smooth progress bar
            
            # 📝 DYNAMIC MSG LOGIC (Now correctly passed to UI)
            msg = "📡 Master is directing traffic..."
            
            if data.get('audio_path'):
                msg = "🎙️ Voice synthesis ready. Finishing up..."
            elif data.get('summary'):
                msg = "🤖 Summary generated by Mistral AI."
            elif data.get('sentiment'):
                msg = "🧠 Sentiment analysis complete."
            elif data.get('text'):
                msg = "📸 OCR/Input text extracted."
            elif data.get('master'):
                msg = "🎮 Orchestrator active (Hub-and-Spoke)."

            # 🎯 UI UPDATE: Yield both the progress/msg string AND the results dict
            # Your AnalyzerUI.render loop checks: if isinstance(info, str) -> update status_text
            yield progress, msg
            yield progress, results 
            
            # Check for Final Completion
            if data.get('status') == 'COMPLETED':
                results["status"] = "COMPLETE"
                yield 1.0, "✅ All Cloud Workers finished!"
                yield 1.0, results
                return

        results["status"] = "TIMEOUT"
        yield 1.0, results

    def get_user_feedback(self, username):
        """Used by HistoryUI to list previous analyses."""
        try:
            table = self.dynamodb.Table('Analysis_Summaries')
            response = table.scan(FilterExpression=Attr('user_id').eq(username))
            items = response.get('Items', [])
            return sorted(items, key=lambda x: x.get('timestamp', ''), reverse=True)
        except Exception as e:
            self.logger.log_event("DATABASE", "ERROR", f"Error: {e}")
            return []

    def _get_table_data(self, table_name, feedback_id):
        """Matches the 'feedback_id' HASH key found in describe-table."""
        try:
            table = self.dynamodb.Table(table_name)
            response = table.get_item(Key={'feedback_id': feedback_id}) # Fixed key name
            return response.get('Item')
        except Exception as e:
            self.logger.log_event("DB_POLLING", "ERROR", f"Error: {e}")
            return None